- name: Install common packages (raspberry)
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: yes
  pre_tasks:
    - name: Update apt cache
      apt: upgrade=no update_cache=yes cache_valid_time=999999
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  tasks:

    - name: "Install standard Raspbian packages"
      apt:
        name: "{{item}}"
        state: present
        update_cache: no
        #yes
      #when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
      with_items:
        - joystick
        - sshfs

    # presupposes the ssh-fs package above
    - name: "Allow other users to use fuse"
      copy:
        content: |
          # /etc/fuse.conf - Configuration file for Filesystem in Userspace (FUSE)
          user_allow_other
        dest: /etc/fuse.conf
        owner: root
